services:
  nginx:
    build:
      context: ../../..
      dockerfile: ./services/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
  web:
    restart: always
    image: web:prod
    build:
      context: ../../..
      dockerfile: config/docker/prod/web.Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 --timeout 600 --worker-class=gevent run_web:server
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_QUEUE: backend_challenge_jobs
      MONGO_HOST: mongo
      MONGO_DB: backend_challenge_jobs
    expose:
      - 5000
    depends_on:
      - rabbitmq
      - mongodb
  worker:
    restart: always
    image: worker:prod
    build:
      context: ../../..
      dockerfile: config/docker/prod/worker.Dockerfile
    command: python run_worker.py
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_QUEUE: backend_challenge_jobs
      MONGO_HOST: mongo
      MONGO_DB: backend_challenge_jobs
    depends_on:
      - rabbitmq
      - mongodb
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    expose:
      - 5672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 3s
      timeout: 10s
      retries: 3
  mongodb:
    hostname: mongo
    image: mongo:latest
    expose:
      - 27017
    restart: always
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
